<?php

namespace App\Models;

use App\Models\Abstracts\BaseModel;
use App\Models\Concerns\LogsModelActivity;
use Database\Factories\LeadFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Lead entity (spec 0024): a contact generated by a campaign. `referent_id`/
 * `campaign_id`/`lead_status_id` are mandatory (BR-1, spec 0029 D-1);
 * `operational_site_id`/`source_id`/`operator_id`/`notes` are optional. No
 * `code` (D-3): unlike Project/Campaign, a Lead carries no sequential
 * identifier. `extra_fields` (spec 0033) is a raw JSON key/value store for
 * free-form data — typed manually on the Lead form or mapped to `__extra__`
 * during the import wizard — deliberately NOT the Universal Custom Fields
 * system (spec 0021).
 */
#[Fillable([
    'referent_id',
    'campaign_id',
    'operational_site_id',
    'source_id',
    'operator_id',
    'lead_status_id',
    'notes',
    'extra_fields',
])]
class Lead extends BaseModel
{
    /** @use HasFactory<LeadFactory> */
    use HasFactory, LogsModelActivity;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'extra_fields' => 'array',
        ];
    }

    public function referent(): BelongsTo
    {
        return $this->belongsTo(Referent::class);
    }

    public function campaign(): BelongsTo
    {
        return $this->belongsTo(Campaign::class);
    }

    public function operationalSite(): BelongsTo
    {
        return $this->belongsTo(OperationalSite::class);
    }

    public function source(): BelongsTo
    {
        return $this->belongsTo(Source::class);
    }

    /**
     * The internal user assigned to work this lead.
     */
    public function operator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'operator_id');
    }

    public function leadStatus(): BelongsTo
    {
        return $this->belongsTo(LeadStatus::class);
    }
}
