<?php

declare(strict_types=1);

namespace App\DataObjects\Projects;

/**
 * Validated payload for creating a project (POST /api/projects, spec 0023).
 *
 * Declared DTO (no "magic flying array") so the StoreProjectRequest ->
 * ProjectService contract is explicit — see standards/architecture.md ->
 * Data Transfer Objects.
 *
 * `code` is intentionally ABSENT: it is generated by the Service inside the
 * create transaction with a pessimistic lock (BR-1) — it is never in
 * $fillable and never accepted from the client.
 */
final readonly class CreateProjectData
{
    public function __construct(
        public string $name,
        public int $projectStatusId,
        public ?string $description,
        public ?int $registryId,
        public ?int $sourceId,
        public ?int $businessFunctionId,
        public ?int $stateId,
        public ?int $productCategoryId,
        public ?int $partnerId,
        public ?string $startDate,
        public ?string $endDate,
        public ?float $totalBudget,
        public ?int $targetLead,
    ) {}

    /**
     * Build from the validated StoreProjectRequest payload.
     *
     * @param  array<string, mixed>  $data
     */
    public static function fromValidated(array $data): self
    {
        return new self(
            name: (string) $data['name'],
            projectStatusId: (int) $data['project_status_id'],
            description: $data['description'] ?? null,
            registryId: isset($data['registry_id']) ? (int) $data['registry_id'] : null,
            sourceId: isset($data['source_id']) ? (int) $data['source_id'] : null,
            businessFunctionId: isset($data['business_function_id']) ? (int) $data['business_function_id'] : null,
            stateId: isset($data['state_id']) ? (int) $data['state_id'] : null,
            productCategoryId: isset($data['product_category_id']) ? (int) $data['product_category_id'] : null,
            partnerId: isset($data['partner_id']) ? (int) $data['partner_id'] : null,
            startDate: $data['start_date'] ?? null,
            endDate: $data['end_date'] ?? null,
            totalBudget: isset($data['total_budget']) ? (float) $data['total_budget'] : null,
            targetLead: isset($data['target_lead']) ? (int) $data['target_lead'] : null,
        );
    }

    /**
     * The project attributes for a mass-assignment create (framework array
     * boundary). `code` is NOT included: the Service merges it in separately
     * once generated (BR-1).
     *
     * @return array<string, mixed>
     */
    public function attributes(): array
    {
        return [
            'name' => $this->name,
            'project_status_id' => $this->projectStatusId,
            'description' => $this->description,
            'registry_id' => $this->registryId,
            'source_id' => $this->sourceId,
            'business_function_id' => $this->businessFunctionId,
            'state_id' => $this->stateId,
            'product_category_id' => $this->productCategoryId,
            'partner_id' => $this->partnerId,
            'start_date' => $this->startDate,
            'end_date' => $this->endDate,
            'total_budget' => $this->totalBudget,
            'target_lead' => $this->targetLead,
        ];
    }
}
