/**
 * Leads domain (spec 0024). Sibling file so `en.ts` stays within the
 * engineering size limits (see `.claude/rules/engineering.md` §6).
 */

export const leads = {
  title: 'Leads',
  subtitle: 'Browse, filter and manage the leads generated by your organization campaigns.',
  forbidden: "You don't have permission to view leads.",
  columns: {
    referent: 'Contact',
    campaign: 'Campaign',
    operational_site: 'Site',
    source: 'Source',
    operator: 'Operator',
    notes: 'Notes',
    created_at: 'Created at',
  },
  detail: {
    title: 'Lead details',
    subtitle: 'Read-only view of the selected lead.',
    loadError: 'Unable to load the lead. Please try again.',
    unknownReferent: 'Unknown contact',
  },
  status: {
    converted: 'Converted',
    notConverted: 'Not converted',
  },
  form: {
    newLead: 'New lead',
    createTitle: 'Create lead',
    createSubtitle: 'Add a new lead to your organization.',
    editTitle: 'Edit lead',
    editSubtitle: 'Update the selected lead.',
    sections: {
      contact: {
        title: 'Contact & campaign',
        description: 'The contact and the campaign that generated it, plus site, source and operator.',
      },
      details: {
        title: 'Details',
        description: 'Site, source and operator associated with the lead.',
      },
      notes: {
        title: 'Notes',
        description: 'Free-form notes about the lead.',
      },
    },
    referent: 'Contact',
    referentSearch: 'Search contacts…',
    referentRequired: 'Contact is required.',
    campaign: 'Campaign',
    campaignSearch: 'Search campaigns…',
    campaignRequired: 'Campaign is required.',
    operationalSite: 'Site',
    operationalSiteSearch: 'Search sites…',
    source: 'Source',
    sourceSearch: 'Search sources…',
    operator: 'Operator',
    operatorSearch: 'Search operators…',
    isConverted: 'Converted lead',
    notes: 'Notes',
    notesMax: 'Notes must be at most 5000 characters.',
    selectPlaceholder: 'Select…',
    selectEmpty: 'No results found.',
    selectError: 'Unable to load the options.',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    created: 'Lead created successfully.',
    updated: 'Lead updated successfully.',
    deleted: 'Lead deleted successfully.',
    genericError: 'Something went wrong. Please try again.',
    deleteError: 'Unable to delete the lead. Please try again.',
    deleteForbidden: 'You cannot delete this lead.',
  },
}
