<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Project entity (spec 0023): may stand alone or own Campaigns (which then
 * inherit its status/business-function/region/product-category — see
 * `campaigns` migration). `code` (PRJ-0001...) is generated by the service
 * inside the create transaction (BR-1): NOT in the model's #[Fillable].
 * `project_status_id` is required and `restrictOnDelete` (BR-4). Every other
 * classification FK is optional and `nullOnDelete` (losing the referenced row
 * just clears the field, it never cascades a delete of the project).
 * `total_budget` mirrors the Product decimal(15,2) convention; lowering it
 * below the sum already allocated to its campaigns is allowed (D-4) — the
 * check only ever flows the other way, from campaign to project (BR-3).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('code', 32)->unique();
            $table->string('name', 191);
            $table->text('description')->nullable();
            $table->foreignId('registry_id')->nullable()->constrained('registries')->nullOnDelete();
            $table->foreignId('project_status_id')->constrained('project_statuses')->restrictOnDelete();
            $table->foreignId('source_id')->nullable()->constrained('sources')->nullOnDelete();
            $table->foreignId('business_function_id')->nullable()->constrained('business_functions')->nullOnDelete();
            $table->foreignId('state_id')->nullable()->constrained('states')->nullOnDelete();
            $table->foreignId('product_category_id')->nullable()->constrained('product_categories')->nullOnDelete();
            $table->foreignId('partner_id')->nullable()->constrained('referents')->nullOnDelete();
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
            $table->decimal('total_budget', 15, 2)->nullable();
            $table->unsignedInteger('target_lead')->nullable();
            $table->timestamps();

            $table->index('project_status_id');
            $table->index('registry_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('projects');
    }
};
