<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Lead entity (spec 0024): a contact generated by a campaign. Ties a
 * Referent (the contact) to a Campaign, optionally to an OperationalSite, a
 * Source and an Operator (User), plus free-text notes. No `code` (D-3): a
 * Lead has none of Project/Campaign's sequential identifier.
 *
 * BR-2/D-4: cancellation is BLOCKING on every one of the 5 relations —
 * `restrictOnDelete()` on all of them, mirrored at the app layer by a
 * `abort(409, ...)` guard in each referenced module's Service (see
 * CampaignService/ReferentService/OperationalSiteService/SourceService/
 * UserService). Without the app-layer guard, the DB-level restrict would
 * surface as a raw QueryException (500), not a clean 409.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->id();
            $table->foreignId('referent_id')->constrained('referents')->restrictOnDelete();
            $table->foreignId('campaign_id')->constrained('campaigns')->restrictOnDelete();
            $table->foreignId('operational_site_id')->nullable()->constrained('operational_sites')->restrictOnDelete();
            $table->foreignId('source_id')->nullable()->constrained('sources')->restrictOnDelete();
            $table->foreignId('operator_id')->nullable()->constrained('users')->restrictOnDelete();
            $table->text('notes')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('leads');
    }
};
