<?php

namespace Database\Seeders;

use App\DataObjects\Projects\CreateProjectData;
use App\Models\BusinessFunction;
use App\Models\Campaign;
use App\Models\Country;
use App\Models\ProductCategory;
use App\Models\Project;
use App\Models\ProjectStatus;
use App\Models\Referent;
use App\Models\Registry;
use App\Models\Source;
use App\Models\State;
use App\Services\ProjectService;
use Faker\Factory as FakerFactory;
use Faker\Generator;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

/**
 * Development seed for the projects module (spec 0023).
 *
 * Every project is created through ProjectService::create() — the same path
 * POST /api/projects uses — so the BR-1 sequential `code` (PRJ-0001...) is
 * generated by the real locked mechanism rather than reproduced here.
 * Classification FKs are drawn round-robin from the lookups seeded earlier
 * in DemoDataSeeder (registries/sources/business-functions/product-categories
 * seeded via their own Demo*Seeder, states via `locations:add`, partner via
 * DemoReferentSeeder), degrading gracefully to null when a lookup produced no
 * rows. `state_id` is scoped to Italy's regions: this gestionale's demo data
 * is Italian-flavoured (it_IT faker across the other seeders).
 *
 * Depends on DemoProjectStatusSeeder, DemoRegistrySeeder, DemoSourceSeeder,
 * DemoBusinessFunctionSeeder, DemoProductCatalogSeeder and DemoReferentSeeder
 * — must run after all of them. Idempotent: existing campaigns and projects
 * are cleared first (campaigns before projects — `campaigns.project_id` is
 * `restrictOnDelete`, BR-5 — so a stale campaign would block the project
 * delete on a second run); DemoCampaignSeeder recreates the campaigns right
 * after this seeder runs.
 */
class DemoProjectSeeder extends Seeder
{
    private const int PROJECTS = 14;

    private const int STATE_SAMPLE = 20;

    public function __construct(private readonly ProjectService $projects) {}

    public function run(): void
    {
        // Children first (restrictOnDelete guard, BR-5): a stale campaign from
        // a previous run would otherwise block deleting its project below.
        // DemoCampaignSeeder repopulates campaigns right after this seeder.
        Campaign::query()->delete();
        Project::query()->delete();

        $faker = FakerFactory::create('it_IT');
        $faker->seed(20260713);

        $statuses = ProjectStatus::query()->orderBy('sort_order')->get();
        $registries = Registry::query()->orderBy('id')->get();
        $sources = Source::query()->orderBy('name')->get();
        $businessFunctions = BusinessFunction::query()->orderBy('name')->get();
        $productCategories = ProductCategory::query()->orderBy('name')->get();
        $partners = Referent::query()->orderBy('name')->get();
        $states = $this->italianStates();

        if ($statuses->isEmpty()) {
            // No status to satisfy the NOT NULL project_status_id (BR-4/D-5):
            // nothing sensible to seed without it.
            return;
        }

        for ($index = 0; $index < self::PROJECTS; $index++) {
            $this->seedProject($faker, $index, $statuses, $registries, $sources, $businessFunctions, $states, $productCategories, $partners);
        }
    }

    /**
     * @param  Collection<int, ProjectStatus>  $statuses
     * @param  Collection<int, Registry>  $registries
     * @param  Collection<int, Source>  $sources
     * @param  Collection<int, BusinessFunction>  $businessFunctions
     * @param  Collection<int, State>  $states
     * @param  Collection<int, ProductCategory>  $productCategories
     * @param  Collection<int, Referent>  $partners
     */
    private function seedProject(
        Generator $faker,
        int $index,
        Collection $statuses,
        Collection $registries,
        Collection $sources,
        Collection $businessFunctions,
        Collection $states,
        Collection $productCategories,
        Collection $partners,
    ): void {
        // Every 5th project has no budget cap at all (A-1): campaigns linked
        // to it are never constrained by BR-3.
        $hasBudgetCap = $index % 5 !== 0;
        $startDate = $faker->dateTimeBetween('-18 months', '+1 month');
        $endDate = $faker->boolean(70)
            ? (clone $startDate)->modify('+'.$faker->numberBetween(2, 14).' months')
            : null;

        $data = new CreateProjectData(
            name: $faker->unique()->catchPhrase(),
            projectStatusId: $statuses[$index % $statuses->count()]->id,
            description: $faker->boolean(60) ? $faker->paragraph() : null,
            registryId: $this->pick($registries, $index)?->id,
            sourceId: $this->pick($sources, $index)?->id,
            businessFunctionId: $this->pick($businessFunctions, $index)?->id,
            stateId: $this->pick($states, $index)?->id,
            productCategoryId: $this->pick($productCategories, $index)?->id,
            partnerId: $this->pick($partners, $index)?->id,
            startDate: $startDate->format('Y-m-d'),
            endDate: $endDate?->format('Y-m-d'),
            totalBudget: $hasBudgetCap ? $faker->randomFloat(2, 5000, 250000) : null,
            targetLead: $faker->boolean(80) ? $faker->numberBetween(5, 300) : null,
        );

        $this->projects->create($data);
    }

    /**
     * @template TModel of \Illuminate\Database\Eloquent\Model
     *
     * @param  Collection<int, TModel>  $items
     * @return TModel|null
     */
    private function pick(Collection $items, int $index): mixed
    {
        return $items->isNotEmpty() ? $items[$index % $items->count()] : null;
    }

    /**
     * Italy's regions ("Regione"), sampled from the `states` geo table seeded
     * by `locations:add` — this gestionale's demo data is Italian-flavoured,
     * so scoping to Italy keeps the values meaningful instead of a random
     * worldwide region.
     *
     * @return Collection<int, State>
     */
    private function italianStates(): Collection
    {
        $italy = Country::query()->where('iso2', 'IT')->first();

        if ($italy === null) {
            return State::query()->inRandomOrder()->limit(self::STATE_SAMPLE)->get();
        }

        return State::query()->where('country_id', $italy->id)->orderBy('name')->get();
    }
}
