<?php

declare(strict_types=1);

namespace App\DataObjects\Campaigns;

/**
 * Validated payload for creating a campaign (POST /api/campaigns, spec 0023).
 *
 * Declared DTO (no "magic flying array") so the StoreCampaignRequest ->
 * CampaignService contract is explicit — see standards/architecture.md ->
 * Data Transfer Objects.
 *
 * `code` is intentionally ABSENT: it is generated by the Service inside the
 * create transaction with a pessimistic lock (BR-1) — never in $fillable,
 * never accepted from the client (AC-029).
 */
final readonly class CreateCampaignData
{
    public function __construct(
        public ?int $projectId,
        public string $name,
        public ?string $description,
        public ?int $registryId,
        public ?int $sourceId,
        public ?int $partnerId,
        public ?int $projectStatusId,
        public ?int $businessFunctionId,
        public ?int $stateId,
        public ?int $productCategoryId,
        public ?string $startDate,
        public ?string $endDate,
        public ?float $totalBudget,
        public ?int $targetLead,
    ) {}

    /**
     * Build from the validated StoreCampaignRequest payload. The 4
     * classification fields are validated `prohibited` when `project_id` is
     * set (BR-2), so they are simply absent from $data in that case.
     *
     * @param  array<string, mixed>  $data
     */
    public static function fromValidated(array $data): self
    {
        return new self(
            projectId: isset($data['project_id']) ? (int) $data['project_id'] : null,
            name: (string) $data['name'],
            description: $data['description'] ?? null,
            registryId: isset($data['registry_id']) ? (int) $data['registry_id'] : null,
            sourceId: isset($data['source_id']) ? (int) $data['source_id'] : null,
            partnerId: isset($data['partner_id']) ? (int) $data['partner_id'] : null,
            projectStatusId: isset($data['project_status_id']) ? (int) $data['project_status_id'] : null,
            businessFunctionId: isset($data['business_function_id']) ? (int) $data['business_function_id'] : null,
            stateId: isset($data['state_id']) ? (int) $data['state_id'] : null,
            productCategoryId: isset($data['product_category_id']) ? (int) $data['product_category_id'] : null,
            startDate: $data['start_date'] ?? null,
            endDate: $data['end_date'] ?? null,
            totalBudget: isset($data['total_budget']) ? (float) $data['total_budget'] : null,
            targetLead: isset($data['target_lead']) ? (int) $data['target_lead'] : null,
        );
    }

    /**
     * Whether this campaign is linked to a project (BR-2).
     */
    public function isLinkedToProject(): bool
    {
        return $this->projectId !== null;
    }

    /**
     * The campaign attributes for a mass-assignment create (framework array
     * boundary). `code` is NOT included: the Service merges it in separately
     * once generated (BR-1). The 4 classification fields are forced null here
     * when linked (BR-2) as defence in depth, on top of the FormRequest's
     * `prohibited` rule.
     *
     * @return array<string, mixed>
     */
    public function attributes(): array
    {
        $linked = $this->isLinkedToProject();

        return [
            'project_id' => $this->projectId,
            'name' => $this->name,
            'description' => $this->description,
            'registry_id' => $this->registryId,
            'source_id' => $this->sourceId,
            'partner_id' => $this->partnerId,
            'project_status_id' => $linked ? null : $this->projectStatusId,
            'business_function_id' => $linked ? null : $this->businessFunctionId,
            'state_id' => $linked ? null : $this->stateId,
            'product_category_id' => $linked ? null : $this->productCategoryId,
            'start_date' => $this->startDate,
            'end_date' => $this->endDate,
            'total_budget' => $this->totalBudget,
            'target_lead' => $this->targetLead,
        ];
    }
}
