import type { LucideIcon } from 'lucide-react'
import {
  Activity, AlarmClock, AtSign, Award, BadgeCheck, BarChart3, Bell, Bike, Book,
  BookOpen, Bookmark, Box, Briefcase, Building, Building2, Calculator, Calendar,
  CalendarDays, Camera, Car, CheckCircle2, ClipboardList, Clock, Cloud, Code,
  Coffee, Cog, Coins, Compass, CreditCard, Database, DollarSign, Download,
  Droplet, Euro, Eye, Factory, File, FileText, Files, Filter, Flag, Flame,
  Folder, Gauge, Gem, Gift, Globe, GraduationCap, Hammer, HardDrive, HardHat,
  Hash, Headphones, Heart, Home, IdCard, Image, Inbox, Info, Key, Landmark,
  Laptop, Layers, LayoutGrid, Leaf, Lightbulb, LineChart, Link, List, Lock,
  Mail, Map, MapPin, Medal, MessageCircle, MessageSquare, Mic, Monitor, Moon,
  Music, Navigation, Package, Paperclip, PenLine, Percent, Phone, PieChart,
  PiggyBank, Plane, Plug, Printer, Puzzle, Receipt, Rocket, Route, Ruler,
  Send, Server, Settings, Shield, ShieldCheck, ShoppingBag, ShoppingCart,
  Signature, SlidersHorizontal, Smartphone, Smile, Sparkles, Star, Store, Sun,
  Table, Tablet, Tag, Tags, Target, ThumbsUp, Ticket, Timer, Trophy, Truck,
  Type, User, Users, Utensils, Video, Wallet, Warehouse, Waypoints, Wifi,
  Wine, Wrench, Zap,
} from 'lucide-react'

/**
 * Curated, bundle-safe catalogue of lucide icons selectable for a custom field
 * definition's `icon` (and each enum option's `icon`). The full lucide set is
 * ~1600 glyphs; importing all of them would bloat the client bundle, so this is
 * a broad-but-finite whitelist of the icons that actually make sense as a
 * field/badge glyph in this admin. Keys are lucide's canonical kebab-case names
 * (the value persisted on the definition), so a stored `icon` survives library
 * upgrades. Shared by both the picker (Phase 1) and the runtime field render
 * (Phase 2) via {@link DynamicIcon}.
 */
export const ICON_CATALOG: Record<string, LucideIcon> = {
  tag: Tag,
  tags: Tags,
  star: Star,
  flag: Flag,
  bookmark: Bookmark,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  smile: Smile,
  award: Award,
  'badge-check': BadgeCheck,
  medal: Medal,
  trophy: Trophy,
  gem: Gem,
  sparkles: Sparkles,
  gift: Gift,
  ticket: Ticket,
  rocket: Rocket,
  lightbulb: Lightbulb,
  zap: Zap,
  flame: Flame,
  target: Target,
  info: Info,
  bell: Bell,
  eye: Eye,
  user: User,
  users: Users,
  'id-card': IdCard,
  signature: Signature,
  briefcase: Briefcase,
  mail: Mail,
  'at-sign': AtSign,
  phone: Phone,
  send: Send,
  inbox: Inbox,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  paperclip: Paperclip,
  link: Link,
  globe: Globe,
  map: Map,
  'map-pin': MapPin,
  navigation: Navigation,
  compass: Compass,
  route: Route,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clock: Clock,
  'alarm-clock': AlarmClock,
  timer: Timer,
  home: Home,
  building: Building,
  'building-2': Building2,
  store: Store,
  warehouse: Warehouse,
  factory: Factory,
  landmark: Landmark,
  hash: Hash,
  type: Type,
  'pen-line': PenLine,
  ruler: Ruler,
  calculator: Calculator,
  percent: Percent,
  euro: Euro,
  'dollar-sign': DollarSign,
  coins: Coins,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  receipt: Receipt,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  package: Package,
  box: Box,
  truck: Truck,
  car: Car,
  plane: Plane,
  bike: Bike,
  file: File,
  'file-text': FileText,
  files: Files,
  folder: Folder,
  'clipboard-list': ClipboardList,
  book: Book,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  list: List,
  'layout-grid': LayoutGrid,
  table: Table,
  layers: Layers,
  filter: Filter,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  activity: Activity,
  gauge: Gauge,
  database: Database,
  server: Server,
  'hard-drive': HardDrive,
  code: Code,
  cog: Cog,
  settings: Settings,
  'sliders-horizontal': SlidersHorizontal,
  wrench: Wrench,
  hammer: Hammer,
  'hard-hat': HardHat,
  key: Key,
  lock: Lock,
  shield: Shield,
  'shield-check': ShieldCheck,
  wifi: Wifi,
  plug: Plug,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  smartphone: Smartphone,
  printer: Printer,
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  mic: Mic,
  headphones: Headphones,
  download: Download,
  'check-circle-2': CheckCircle2,
  puzzle: Puzzle,
  waypoints: Waypoints,
  coffee: Coffee,
  utensils: Utensils,
  wine: Wine,
  leaf: Leaf,
  droplet: Droplet,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
}

/** Sorted list of selectable icon names (the picker's grid + search source). */
export const ICON_NAMES: readonly string[] = Object.keys(ICON_CATALOG).sort()

/** Whether a stored `icon` value maps to a glyph in the catalogue. */
export function isKnownIconName(name: string | null | undefined): name is string {
  return typeof name === 'string' && name in ICON_CATALOG
}
